services:
  payload:
    image: node:22-alpine
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    depends_on:
      - postgres
    env_file:
      - .env.local

  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.local
    restart: always

volumes:
  pgdata:
  node_modules:
