export const CONSTANTS = {
  requestUrl: 'https://localhost/api/fakeEndpoint',
  generalUrl: 'https://localhost',
  stripeUrl: 'https://stripe.com',
  apiHeaders: { 'Content-Type': 'application/json' },
  email: 'test@test.com',
  email2: 'test2@test.com',
  name: 'name',
  invalidEmail: 'invalidEmail',
  phone: '3603334444',
  phone11Diget: '13603334444',
  invalidPhone: '4444',
  address: 'some address',
  sessionId: 'sessionId',
  language: 'en',
  invalidLanguage: 'en2',
  ref: 'ref',
  slug: 'slug',
  searchQuery: 'searchQuery',
  genericObject: { test: 'test' },
  generalId: 'generalId',
  monetaryAmount: '20.00',
  monetaryAmountWithSymbol: '$20.00',
  invalidMonetaryAmount: 'abc',
  monetaryAmountInCents: 2000,
  itemName: 'itemName',
  itemTypeDonation: 'DONATION',
  itemTypeMembership: 'MEMBERSHIP',
  activeMembershipReason: 'ACTIVE_MEMBERSHIP',
  stripeEventId: 'stripeEventId',
  stripeEventType: 'checkout.session.completed',
  emailSlugMebership: 'membership-receipt',
  emailSlugDonation: 'donation-receipt',
}

test('Constants file loads', () => {
  expect(CONSTANTS).toBeDefined()
})
